resource_group_location = "West Europe"
source_control_git_url = "https://github.com/100QNKolev/TaskBoard"
storage_account_name = "contactbooksa"
server_admin_username = "missadministrator"
server_admin_password = "thisIsKat11"
database_name = "contactBookDB"
firewall_name = "contactBookFR"